name: HYPERZONE
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.1.1
  share_plus: ^10.0.0  
  uuid: ^4.5.2
  url_launcher: ^6.3.2
  youtube_player_iframe: ^5.2.2
  intl: ^0.18.1
  url_strategy: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/games/valorant_bg.jpg
    - assets/games/bgmi_bg.jpg
    - assets/games/freefire_bg.jpg
    - assets/games/csgo_bg.jpg
    - assets/banners/host_banner.png
    - assets/hero_bg_placeholder.png
    - assets/upi_qr.png

                                
